# Generated by Django 4.0.1 on 2022-02-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
